import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const bronsul = localFont({
  src: "./fonts/bronsul/Bronsul.woff",
  variable: "--font-bronsul",
  weight: "100 900",
});

const caviarDreams = localFont({
  src: "./fonts/caviar-dreams/CaviarDreams.woff",
  variable: "--font-dreams",
  weight: "100 900",
});

const caviarDreamsBold = localFont({
  src: "./fonts/caviar-dreams/CaviarDreamsBold.woff",
  variable: "--font-dreams-bold",
  weight: "100 900",
});

const caviarDreamsBoldItalic = localFont({
  src: "./fonts/caviar-dreams/CaviarDreamsBoldItalic.woff",
  variable: "--font-dreams-bold-italic",
  weight: "100 900",
});

const caviarDreamsItalic = localFont({
  src: "./fonts/caviar-dreams/CaviarDreamsItalic.woff",
  variable: "--font-dreams-italic",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bronsul.variable} ${caviarDreams.variable} ${caviarDreamsBold.variable} ${caviarDreamsBoldItalic.variable} ${caviarDreamsItalic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
